//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\city
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 02/08/2021, 22:18:40
//////////////////////////////////////////////////////////////
class CfgPatches
{
	class trerik4_van
	{
		units[] = { "Land_ambulance_van", "Land_military_van" };
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};

class CfgVehicles
{
    class HouseNoDestruct;
    class Land_ambulance_van: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_ambulance_van";
        descriptionShort = "Autogenerated class Land_ambulance_van";
        model = "trerik4\city\van\ambulance_van.p3d";
        hiddenSelections[] = {"lightbar"};
        hiddenSelectionsTextures[] = {"trerik4\city\van\data\lightbar_ca.paa"};
        hiddenSelectionsMaterials[] = {"trerik4\city\van\data\lightbar.rvmat"};

        class AnimatedTexture {
            enabled = 1;
            loop = 1;
            increment = 1;
            interval = 800;
            intervalRandomness = 500;
            renderDistance = 25.0;
            distanceResetsToDefault = 1;
            selectionToAnimate = "lightbar";
            hiddenSelectionsTexturePhases[] = {"", ""};
            hiddenSelectionsMaterialPhases[] = {"trerik4\city\van\data\lightbar0.rvmat", "trerik4\city\van\data\lightbar1.rvmat"};
        };
    };
    class Land_military_van: Land_ambulance_van
    {
        scope = 2;
        displayName = "Land_military_van";
        descriptionShort = "Autogenerated class Land_military_van";
        model = "trerik4\city\van\military_van.p3d";
    };
};