/*
	Less doors be bussin'
*/

class CfgPatches
{
	class trerik4_lessdoors
	{
		units[] = { "Land_door1", "Door1", "Door1Kit" };
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};

class CfgMods
{
	class LessDoors
	{
		type = "mod";
		author = "kerkkoh";
		dir = "trerik4";
		name = "LessDoors";
		dependencies[] = {"Game","World","Mission"};
		class defs
		{
			class gameScriptModule
			{
				value = "";
				files[] = {"trerik4/lessdoors/Scripts/3_Game"};
			};
			class worldScriptModule
			{
				value = "";
				files[] = {"trerik4/lessdoors/Scripts/4_World"};
			};
			class missionScriptModule
			{
				value = "";
				files[] = {"trerik4/lessdoors/Scripts/5_Mission"};
			};
		};
	};
};

class CfgVehicles
{
	class Fence;
	class Inventory_Base;
	class HouseNoDestruct;

    class Land_door1_open: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_door1_open";
        descriptionShort = "Autogenerated class Land_door1_open";
        model = "trerik4\lessdoors\door1_open.p3d";
    };

    class Land_door1: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_door1";
        descriptionShort = "Autogenerated class Land_door1";
        model = "trerik4\lessdoors\door1.p3d";
		class Doors
		{
			class Door1
			{
				displayName = "Door 1";
				component = "door1";
				soundPos = "door1_action";
				animPeriod = 1.0;
				initPhase = 0.0;
				initOpened = 0.5;
				soundOpen = "doorWoodFrontOpen";
				soundClose = "doorWoodFrontClose";
				soundLocked = "doorWoodFrontRattle";
				soundOpenABit = "doorWoodFrontOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 1000000;
				};
			};
			class GlobalArmor
			{
				class Projectile
				{
					class Health { damage = 0; };
					class Blood { damage = 0; };
					class Shock { damage = 0; };
				};
				class Melee
				{
					class Health { damage = 0; };
					class Blood { damage = 0; };
					class Shock { damage = 0; };
				};
			};
			class DamageZones
			{
				class Door1
				{
					class Health
					{
						hitpoints = 1000;
						transferToGlobalCoef = 0;
					};
					componentNames[] = {"door1"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile
						{
							class Health { damage = 2; };
							class Blood { damage = 0; };
							class Shock { damage = 0; };
						};
						class Melee
						{
							class Health { damage = 2.5; };
							class Blood { damage = 0; };
							class Shock { damage = 0; };
						};
					};
				};
			};
		};
    };
	class Land_door2: Land_door1 {
        scope = 2;
        displayName = "Land_door2";
        descriptionShort = "Autogenerated class Land_door2";
        model = "trerik4\lessdoors\door2.p3d";
	};

	class DoorBase: Inventory_Base
	{
		scope = 2;
		displayName = "Door";
		descriptionShort = "A simple door.";
		model = "\trerik4\lessdoors\door1_buildable.p3d";
		attachments[] = {"Att_CombinationLock"};
		hybridAttachments[] = {};
		mountables[] = {};
		overrideDrawArea = "3.0";
		forceFarBubble = "true";
		lootCategory = "Crafted";
		carveNavmesh = 1;
		weight = 10000;
		itemSize[] = {2,3};
		physLayer = "item_large";
		rotationFlags = 2;
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 9999990;
				};
			};
			class GlobalArmor
			{
				class Projectile
				{
					class Health
					{
						damage = 0;
					};
					class Blood
					{
						damage = 0;
					};
					class Shock
					{
						damage = 0;
					};
				};
				class Melee
				{
					class Health
					{
						damage = 0;
					};
					class Blood
					{
						damage = 0;
					};
					class Shock
					{
						damage = 0;
					};
				};
				class FragGrenade
				{
					class Health
					{
						damage = 0;
					};
					class Blood
					{
						damage = 0;
					};
					class Shock
					{
						damage = 0;
					};
				};
			};
		};
		class GUIInventoryAttachmentsProps
		{
			/* class Base
			{
				name = "$STR_CfgVehicles_Fence_Att_Category_Base";
				description = "";
				attachmentSlots[] = {"Att_CombinationLock"};
				icon = "cat_bb_base";
				selection = "wall";
			}; */
			class Attachments
			{
				name = "$STR_CfgVehicles_Fence_Att_Category_Attachments";
				description = "";
				attachmentSlots[] = {"Att_CombinationLock"};// {"Wall_Camonet","Wall_Barbedwire_1","Wall_Barbedwire_2"};
				icon = "set:dayz_inventory image:cat_bb_attachments";
				selection = "wall";
			};
			/* class Material
			{
				name = "$STR_CfgVehicles_Fence_Att_Category_Materials";
				description = "";
				attachmentSlots[] = {"Material_Nails","Material_WoodenPlanks","Material_MetalSheets","Material_MetalWire"};
				icon = "cat_bb_material";
				selection = "wall";
			}; */
		};
		class AnimationSources
		{
/* 			class AnimSourceShown
			{
				source = "user";
				animPeriod = 0.01;
				initPhase = 0;
			};
			class AnimSourceHidden
			{
				source = "user";
				animPeriod = 0.01;
				initPhase = 1;
			};*/
			class AnimRotate
			{
				source = "user";
				animPeriod = 1.0;
				initPhase = 0;
				initOpened = 0.5;
			};
/* 			class Wall_Interact_Rotate: AnimRotate{};
			class Wall_Barbedwire_1_Mounted_Rotate: AnimRotate{};
			class Wall_Barbedwire_2_Mounted_Rotate: AnimRotate{};
			class Wall_Camonet_Rotate: AnimRotate{}; */
			class Wall_Gate_Rotate: AnimRotate{};
/* 			class Wall_Base_Down_Rotate: AnimRotate{};
			class Wall_Base_Up_Rotate: AnimRotate{};
			class Wall_Wood_Down_Rotate: AnimRotate{};
			class Wall_Wood_Up_Rotate: AnimRotate{};
			class Wall_Metal_Down_Rotate: AnimRotate{};
			class Wall_Metal_Up_Rotate: AnimRotate{};
			class Material_WoodenLogs: AnimSourceHidden{};
			class Material_MetalWire: AnimSourceHidden{};
			class Wall_Barbedwire_1: AnimSourceHidden{};
			class Wall_Barbedwire_1_Mounted: AnimSourceHidden{};
			class Wall_Barbedwire_2: AnimSourceHidden{};
			class Wall_Barbedwire_2_Mounted: AnimSourceHidden{};
			class Wall_Camonet: AnimSourceHidden{};
			class Deployed: AnimSourceHidden{};
			class Base: AnimSourceHidden{};
			class Wall_Platform: AnimSourceHidden{};
			class Wall_Platform_Stairs_Left: AnimSourceHidden{};
			class Wall_Platform_Stairs_Right: AnimSourceHidden{};
			class Wall_Gate: AnimSourceHidden{};
			class Wall_Base_Down: AnimSourceHidden{};
			class Wall_Base_Up: AnimSourceHidden{};
			class Wall_Metal_Down: AnimSourceHidden{};
			class Wall_Metal_Up: AnimSourceHidden{};
			class Wall_Wood_Down: AnimSourceHidden{};
			class Wall_Wood_Up: AnimSourceHidden{}; */
		};/* 
		class Construction
		{
			class wall
			{
				class wall_gate
				{
					name = "$STR_CfgVehicles_Construction_Part_Gate";
					is_gate = 1;
					id = 5;
					required_parts[] = {};
					conflicted_parts[] = {};
					collision_data[] = {};
					build_action_type = 1;
					dismantle_action_type = 1;
					material_type = 5;
				};
			};
		}; */
	};
	class Door1: DoorBase {};

	//class WoodenCrate;
	class DoorKit: Inventory_Base
	{
		scope = 0;
		displayName = "Door Kit";
		descriptionShort = "Door Kit";
		model = "\DZ\gear\camping\wooden_case.p3d";
		itemSize[] = {5,3};
		canBeDigged = 0;
		rotationFlags = 2;
		itemBehaviour = 2;
		weight = 300;
	};
	class Door1Kit: DoorKit {
		scope = 2;
	};
};