//////////////////////////////////////////////////////////////
// DayZ Config Generator: trerik4\city\basebuilding
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 10/04/2021, 01:06:31
// `py config_generator.py -o P:\ P:\trerik4\city\basebuilding`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_basebuilding
    {
        units[] = { "Land_basebuilding_bigbridge", "Land_basebuilding_longplanks", "Land_basebuilding_metalshit", "Land_basebuilding_shortplanks", "Land_basebuilding_slimpole", "Land_basebuilding_thicpole" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_basebuilding_bigbridge: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_basebuilding_bigbridge";
        descriptionShort = "Autogenerated class Land_basebuilding_bigbridge";
        model = "trerik4\city\basebuilding\basebuilding_bigbridge.p3d";
    };
    class Land_basebuilding_longplanks: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_basebuilding_longplanks";
        descriptionShort = "Autogenerated class Land_basebuilding_longplanks";
        model = "trerik4\city\basebuilding\basebuilding_longplanks.p3d";
    };
    class Land_basebuilding_metalshit: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_basebuilding_metalshit";
        descriptionShort = "Autogenerated class Land_basebuilding_metalshit";
        model = "trerik4\city\basebuilding\basebuilding_metalshit.p3d";
    };
    class Land_basebuilding_shortplanks: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_basebuilding_shortplanks";
        descriptionShort = "Autogenerated class Land_basebuilding_shortplanks";
        model = "trerik4\city\basebuilding\basebuilding_shortplanks.p3d";
    };
    class Land_basebuilding_slimpole: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_basebuilding_slimpole";
        descriptionShort = "Autogenerated class Land_basebuilding_slimpole";
        model = "trerik4\city\basebuilding\basebuilding_slimpole.p3d";
    };
    class Land_basebuilding_thicpole: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_basebuilding_thicpole";
        descriptionShort = "Autogenerated class Land_basebuilding_thicpole";
        model = "trerik4\city\basebuilding\basebuilding_thicpole.p3d";
    };
};