//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\city\zoo
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 05/07/2022, 13:46:33
// `py config_generator.py -d -o F:\DayZ P:\trerik4\city\zoo`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_zoo
    {
        units[] = { "Land_Zoo_Entrance_Scale" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_Zoo_Entrance_Scale: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_Zoo_Entrance_Scale";
        descriptionShort = "Autogenerated class Land_Zoo_Entrance_Scale";
        model = "trerik4\city\zoo\Zoo_Entrance_Scale.p3d";
    };
};