//////////////////////////////////////////////////////////////
// DayZ Config Generator: trerik4\city\modular\vents
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 10/31/2021, 12:13:26
// `py config_generator.py -o P:\ P:\trerik4\city\modular\vents`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_vents
    {
        units[] = { "Land_vent_straight", "Land_vent_tube_curved", "Land_vent_tube_straight" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_vent_straight: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_vent_straight";
        descriptionShort = "Autogenerated class Land_vent_straight";
        model = "trerik4\city\modular\vents\vent_straight.p3d";
    };
    class Land_vent_tube_curved: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_vent_tube_curved";
        descriptionShort = "Autogenerated class Land_vent_tube_curved";
        model = "trerik4\city\modular\vents\vent_tube_curved.p3d";
    };
    class Land_vent_tube_straight: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_vent_tube_straight";
        descriptionShort = "Autogenerated class Land_vent_tube_straight";
        model = "trerik4\city\modular\vents\vent_tube_straight.p3d";
    };
};