//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\city
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 02/08/2021, 22:18:40
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_blood
    {
        units[] = { "Land_blood_puddleold", "Land_blood_puddlesmallold", "Land_blood_splatterold" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_blood_puddleold: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_blood_puddleold";
        descriptionShort = "Autogenerated class Land_blood_puddleold";
        model = "trerik4\city\blood\blood_puddleold.p3d";
    };
    class Land_blood_puddlesmallold: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_blood_puddlesmallold";
        descriptionShort = "Autogenerated class Land_blood_puddlesmallold";
        model = "trerik4\city\blood\blood_puddlesmallold.p3d";
    };
    class Land_blood_splatterold: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_blood_splatterold";
        descriptionShort = "Autogenerated class Land_blood_splatterold";
        model = "trerik4\city\blood\blood_splatterold.p3d";
    };
};