//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\military\improvised
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 09/11/2021, 20:01:50
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class generated_improvised
    {
        units[] = { "Land_camonet_winter", "Land_camonet_winter_inv", "Land_military_truck_camonet", "Land_truck_camonet" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_camonet_winter: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_camonet_winter";
        descriptionShort = "Autogenerated class Land_camonet_winter";
        model = "trerik4\military\improvised\camonet_winter.p3d";
    };
    class Land_camonet_winter_inv: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_camonet_winter_inv";
        descriptionShort = "Autogenerated class Land_camonet_winter_inv";
        model = "trerik4\military\improvised\camonet_winter_inv.p3d";
    };
    class Land_military_truck_camonet: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_military_truck_camonet";
        descriptionShort = "Autogenerated class Land_military_truck_camonet";
        model = "trerik4\military\improvised\military_truck_camonet.p3d";
    };
    class Land_truck_camonet: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_truck_camonet";
        descriptionShort = "Autogenerated class Land_truck_camonet";
        model = "trerik4\military\improvised\truck_camonet.p3d";
    };
};