//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\nature
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 02/14/2021, 16:10:04
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_nature
    {
        units[] = { "Land_lion", "Land_rock_1", "Land_rock_10", "Land_rock_2", "Land_rock_3", "Land_rock_4", "Land_rock_5", "Land_rock_6", "Land_rock_7", "Land_rock_8", "Land_rock_9", "Land_ice1", "Land_ice2", "Land_ice3" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_lion: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_lion";
        descriptionShort = "Autogenerated class Land_lion";
        model = "trerik4\nature\rocks\lion.p3d";
    };
    class Land_rock_1: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_1";
        descriptionShort = "Autogenerated class Land_rock_1";
        model = "trerik4\nature\rocks\rock_1.p3d";
    };
    class Land_rock_10: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_10";
        descriptionShort = "Autogenerated class Land_rock_10";
        model = "trerik4\nature\rocks\rock_10.p3d";
    };
    class Land_rock_2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_2";
        descriptionShort = "Autogenerated class Land_rock_2";
        model = "trerik4\nature\rocks\rock_2.p3d";
    };
    class Land_rock_3: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_3";
        descriptionShort = "Autogenerated class Land_rock_3";
        model = "trerik4\nature\rocks\rock_3.p3d";
    };
    class Land_rock_4: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_4";
        descriptionShort = "Autogenerated class Land_rock_4";
        model = "trerik4\nature\rocks\rock_4.p3d";
    };
    class Land_rock_5: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_5";
        descriptionShort = "Autogenerated class Land_rock_5";
        model = "trerik4\nature\rocks\rock_5.p3d";
    };
    class Land_rock_6: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_6";
        descriptionShort = "Autogenerated class Land_rock_6";
        model = "trerik4\nature\rocks\rock_6.p3d";
    };
    class Land_rock_7: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_7";
        descriptionShort = "Autogenerated class Land_rock_7";
        model = "trerik4\nature\rocks\rock_7.p3d";
    };
    class Land_rock_8: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_8";
        descriptionShort = "Autogenerated class Land_rock_8";
        model = "trerik4\nature\rocks\rock_8.p3d";
    };
    class Land_rock_9: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_rock_9";
        descriptionShort = "Autogenerated class Land_rock_9";
        model = "trerik4\nature\rocks\rock_9.p3d";
    };
    class Land_ice1: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_ice1";
        descriptionShort = "Autogenerated class Land_ice1";
        model = "trerik4\nature\ice1.p3d";
    };
    class Land_ice2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_ice2";
        descriptionShort = "Autogenerated class Land_ice2";
        model = "trerik4\nature\ice2.p3d";
    };
    class Land_ice3: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_ice3";
        descriptionShort = "Autogenerated class Land_ice3";
        model = "trerik4\nature\ice3.p3d";
    };
};