//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\city
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 02/08/2021, 22:18:40
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik_sheetmetal
    {
        units[] = { "Land_sheetmetal_big", "Land_sheetmetal_blue_big", "Land_sheetmetal_blue_small", "Land_sheetmetal_red_big", "Land_sheetmetal_red_small", "Land_sheetmetal_small", "Land_tin" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_sheetmetal_big: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sheetmetal_big";
        descriptionShort = "Autogenerated class Land_sheetmetal_big";
        model = "trerik4\city\sheetmetal\sheetmetal_big.p3d";
    };
    class Land_sheetmetal_blue_big: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sheetmetal_blue_big";
        descriptionShort = "Autogenerated class Land_sheetmetal_blue_big";
        model = "trerik4\city\sheetmetal\sheetmetal_blue_big.p3d";
    };
    class Land_sheetmetal_blue_small: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sheetmetal_blue_small";
        descriptionShort = "Autogenerated class Land_sheetmetal_blue_small";
        model = "trerik4\city\sheetmetal\sheetmetal_blue_small.p3d";
    };
    class Land_sheetmetal_red_big: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sheetmetal_red_big";
        descriptionShort = "Autogenerated class Land_sheetmetal_red_big";
        model = "trerik4\city\sheetmetal\sheetmetal_red_big.p3d";
    };
    class Land_sheetmetal_red_small: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sheetmetal_red_small";
        descriptionShort = "Autogenerated class Land_sheetmetal_red_small";
        model = "trerik4\city\sheetmetal\sheetmetal_red_small.p3d";
    };
    class Land_sheetmetal_small: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sheetmetal_small";
        descriptionShort = "Autogenerated class Land_sheetmetal_small";
        model = "trerik4\city\sheetmetal\sheetmetal_small.p3d";
    };
    class Land_tin: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tin";
        descriptionShort = "Autogenerated class Land_tin";
        model = "trerik4\city\sheetmetal\tin.p3d";
    };
};