//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\snow
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 03/03/2021, 11:06:23
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_snow
    {
        units[] = { "Land_dirt_pile3", "Land_dirt_pile_half", "Land_dirt_pile_low", "Land_dirt_pile_low_flatbase", "Land_dirt_plane_5", "Land_dirt_plane_50", "Land_grass_plane_5", "Land_snow_pile3", "Land_snow_pile_half", "Land_snow_pile_low", "Land_snow_pile_low_flatbase", "Land_snow_plane_5" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_dirt_pile3: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_dirt_pile3";
        descriptionShort = "Autogenerated class Land_dirt_pile3";
        model = "trerik4\snow\dirt\dirt_pile3.p3d";
    };
    class Land_dirt_pile_half: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_dirt_pile_half";
        descriptionShort = "Autogenerated class Land_dirt_pile_half";
        model = "trerik4\snow\dirt\dirt_pile_half.p3d";
    };
    class Land_dirt_pile_low: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_dirt_pile_low";
        descriptionShort = "Autogenerated class Land_dirt_pile_low";
        model = "trerik4\snow\dirt\dirt_pile_low.p3d";
    };
    class Land_dirt_pile_low_flatbase: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_dirt_pile_low_flatbase";
        descriptionShort = "Autogenerated class Land_dirt_pile_low_flatbase";
        model = "trerik4\snow\dirt\dirt_pile_low_flatbase.p3d";
    };
    class Land_dirt_plane_5: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_dirt_plane_5";
        descriptionShort = "Autogenerated class Land_dirt_plane_5";
        model = "trerik4\snow\dirt\dirt_plane_5.p3d";
    };
    class Land_dirt_plane_50: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_dirt_plane_50";
        descriptionShort = "Autogenerated class Land_dirt_plane_50";
        model = "trerik4\snow\dirt\dirt_plane_50.p3d";
    };
    class Land_grass_plane_5: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_grass_plane_5";
        descriptionShort = "Autogenerated class Land_grass_plane_5";
        model = "trerik4\snow\dirt\grass_plane_5.p3d";
    };
    class Land_snow_pile3: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_snow_pile3";
        descriptionShort = "Autogenerated class Land_snow_pile3";
        model = "trerik4\snow\snow_pile3.p3d";
    };
    class Land_snow_pile_half: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_snow_pile_half";
        descriptionShort = "Autogenerated class Land_snow_pile_half";
        model = "trerik4\snow\snow_pile_half.p3d";
    };
    class Land_snow_pile_low: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_snow_pile_low";
        descriptionShort = "Autogenerated class Land_snow_pile_low";
        model = "trerik4\snow\snow_pile_low.p3d";
    };
    class Land_snow_pile_low_flatbase: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_snow_pile_low_flatbase";
        descriptionShort = "Autogenerated class Land_snow_pile_low_flatbase";
        model = "trerik4\snow\snow_pile_low_flatbase.p3d";
    };
    class Land_snow_plane_5: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_snow_plane_5";
        descriptionShort = "Autogenerated class Land_snow_plane_5";
        model = "trerik4\snow\snow_plane_5.p3d";
    };
};