//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\dpl\props
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 01/21/2022, 01:01:24
// `py config_generator.py -d -o F:\DayZ P:\trerik4\dpl\props`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_props
    {
        units[] = { "Land_A_tent" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_A_tent: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_A_tent";
        descriptionShort = "Autogenerated class Land_A_tent";
        model = "trerik4\dpl\props\A_tent.p3d";
    };
};