//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\city
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 02/08/2021, 22:18:40
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_flag
    {
        units[] = { "Land_flag", "Land_flag_long", "Land_flag_longboi", "Land_flag_longerboi", "Land_flag_longestboi", "Land_flag_pole", "Land_graffiti", "Land_sign", "Land_sign2" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_flag: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_flag";
        descriptionShort = "Autogenerated class Land_flag";
        model = "trerik4\city\flag\flag.p3d";
    };
    class Land_flag_long: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_flag_long";
        descriptionShort = "Autogenerated class Land_flag_long";
        model = "trerik4\city\flag\flag_long.p3d";
    };
    class Land_flag_longboi: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_flag_longboi";
        descriptionShort = "Autogenerated class Land_flag_longboi";
        model = "trerik4\city\flag\flag_longboi.p3d";
    };
    class Land_flag_longerboi: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_flag_longerboi";
        descriptionShort = "Autogenerated class Land_flag_longerboi";
        model = "trerik4\city\flag\flag_longerboi.p3d";
    };
    class Land_flag_longestboi: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_flag_longestboi";
        descriptionShort = "Autogenerated class Land_flag_longestboi";
        model = "trerik4\city\flag\flag_longestboi.p3d";
    };
    class Land_flag_pole: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_flag_pole";
        descriptionShort = "Autogenerated class Land_flag_pole";
        model = "trerik4\city\flag\flag_pole.p3d";
    };
    class Land_sign2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign2";
        descriptionShort = "Autogenerated class Land_sign2";
        model = "trerik4\city\flag\sign2.p3d";
    };
    class Land_trerik4_pole: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_trerik4_pole";
        descriptionShort = "Autogenerated class Land_trerik4_pole";
        model = "trerik4\city\flag\trerik4_pole.p3d";
    };
};

class CfgNonAIVehicles
{
	class StaticObject;
	class Static_Sign : StaticObject
	{
		scope = 2;
		model = "\trerik4\city\flag\sign.p3d";
	};
};
