//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\military\intel
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 01/20/2022, 21:21:49
// `py config_generator.py -d -o F:\DayZ P:\trerik4\military\intel`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_intel
    {
        units[] = { "Land_classified_file" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_classified_file: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_classified_file";
        descriptionShort = "Autogenerated class Land_classified_file";
        model = "trerik4\military\intel\classified_file.p3d";
    };
};