//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\city\nuclear
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 01/20/2022, 21:27:46
// `py config_generator.py -d -o F:\DayZ P:\trerik4\city\nuclear`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_nuclear
    {
        units[] = { "Land_coolingtower" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_coolingtower: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_coolingtower";
        descriptionShort = "Autogenerated class Land_coolingtower";
        model = "trerik4\city\nuclear\coolingtower.p3d";
    };
};