class CfgPatches
{
	class trerik4_bunker
	{
		units[] = {"Land_bunkerdoor_half","Land_bunkerdoor_metal_half"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	class Land_bunkerdoor_half: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerdoor_half";
		descriptionShort = "Autogenerated class Land_bunkerdoor_half";
		model = "trerik4\city\modular\bunker\doors\bunkerdoor_half.p3d";
		class Doors
		{
			class Door1
			{
				displayName = "Door 1";
				component = "door1";
				soundPos = "door1_action";
				animPeriod = 3.0;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSlideHeavyOpen";
				soundClose = "doorMetalSlideHeavyClose";
				soundLocked = "doorMetalSlideHeavyRattle";
				soundOpenABit = "doorMetalSlideHeavyOpenABit";
			};
			class Door2
			{
				displayName = "Door 2";
				component = "door2";
				soundPos = "door2_action";
				animPeriod = 3.0;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSlideHeavyOpen";
				soundClose = "doorMetalSlideHeavyClose";
				soundLocked = "doorMetalSlideHeavyRattle";
				soundOpenABit = "doorMetalSlideHeavyOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 1000000;
				};
			};
			class GlobalArmor
			{
				class Projectile
				{
					class Health
					{
						damage = 0;
					};
					class Blood
					{
						damage = 0;
					};
					class Shock
					{
						damage = 0;
					};
				};
				class Melee
				{
					class Health
					{
						damage = 0;
					};
					class Blood
					{
						damage = 0;
					};
					class Shock
					{
						damage = 0;
					};
				};
			};
			class DamageZones
			{
				class Door1
				{
					class Health
					{
						hitpoints = 1000000;
						transferToGlobalCoef = 0;
					};
					componentNames[] = {"door1"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile
						{
							class Health
							{
								damage = 2;
							};
							class Blood
							{
								damage = 0;
							};
							class Shock
							{
								damage = 0;
							};
						};
						class Melee
						{
							class Health
							{
								damage = 2.5;
							};
							class Blood
							{
								damage = 0;
							};
							class Shock
							{
								damage = 0;
							};
						};
					};
				};
				class Door2
				{
					class Health
					{
						hitpoints = 1000000;
						transferToGlobalCoef = 0;
					};
					componentNames[] = {"door2"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile
						{
							class Health
							{
								damage = 2;
							};
							class Blood
							{
								damage = 0;
							};
							class Shock
							{
								damage = 0;
							};
						};
						class Melee
						{
							class Health
							{
								damage = 2.5;
							};
							class Blood
							{
								damage = 0;
							};
							class Shock
							{
								damage = 0;
							};
						};
					};
				};
			};
		};
	};
	class Land_bunkerdoor_metal_half: Land_bunkerdoor_half
	{
		scope = 2;
		displayName = "Land_bunkerdoor_metal_half";
		descriptionShort = "Autogenerated class Land_bunkerdoor_metal_half";
		model = "trerik4\city\modular\bunker\doors\bunkerdoor_metal_half.p3d";
	};
};
