class CfgPatches
{
	class trerik4_tog_misc
	{
		units[] = { "Land_stairs", "Land_tog_display", "Land_tog_display1", "Land_tog_monorail", "Land_tog_monorail_track", "Land_tog_rail_10", "Land_tog_rail_5", "Land_tog_station", "Land_tog_station2", "Land_tog_tower", "Land_tog_wall" };
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};

class CfgVehicles
{
	class HouseNoDestruct;
    class Land_stairs: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_stairs";
        descriptionShort = "Autogenerated class Land_stairs";
        model = "trerik4\city\tog\stairs.p3d";
    };
    class Land_tog_display: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_display";
        descriptionShort = "Autogenerated class Land_tog_display";
        model = "trerik4\city\tog\tog_display.p3d";
    };
    class Land_tog_display1: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_display1";
        descriptionShort = "Autogenerated class Land_tog_display1";
        model = "trerik4\city\tog\tog_display1.p3d";
    };
    class Land_tog_monorail: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_monorail";
        descriptionShort = "Autogenerated class Land_tog_monorail";
        model = "trerik4\city\tog\tog_monorail.p3d";
		class AnimationSources
		{
			class Move
			{
				source = "user";
				animPeriod = 10.0;
				initPhase = 0;
			};
		};
    };
    class Land_tog_monorail_track: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_monorail_track";
        descriptionShort = "Autogenerated class Land_tog_monorail_track";
        model = "trerik4\city\tog\tog_monorail_track.p3d";
    };
    class Land_tog_rail_10: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_rail_10";
        descriptionShort = "Autogenerated class Land_tog_rail_10";
        model = "trerik4\city\tog\tog_rail_10.p3d";
    };
    class Land_tog_rail_5: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_rail_5";
        descriptionShort = "Autogenerated class Land_tog_rail_5";
        model = "trerik4\city\tog\tog_rail_5.p3d";
    };
    class Land_tog_station: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_station";
        descriptionShort = "Autogenerated class Land_tog_station";
        model = "trerik4\city\tog\tog_station.p3d";
    };
    class Land_tog_station2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_station2";
        descriptionShort = "Autogenerated class Land_tog_station2";
        model = "trerik4\city\tog\tog_station2.p3d";
    };
    class Land_tog_tower: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_tower";
        descriptionShort = "Autogenerated class Land_tog_tower";
        model = "trerik4\city\tog\tog_tower.p3d";
    };
    class Land_tog_wall: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tog_wall";
        descriptionShort = "Autogenerated class Land_tog_wall";
        model = "trerik4\city\tog\tog_wall.p3d";
    };
};