//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\city
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 02/08/2021, 22:18:40
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_garbage
    {
        units[] = { "Land_garbagebags", "Land_garbagebags_withbase" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_garbagebags: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_garbagebags";
        descriptionShort = "Autogenerated class Land_garbagebags";
        model = "trerik4\city\garbage\garbagebags.p3d";
    };
    class Land_garbagebags_withbase: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_garbagebags_withbase";
        descriptionShort = "Autogenerated class Land_garbagebags_withbase";
        model = "trerik4\city\garbage\garbagebags_withbase.p3d";
    };
};