//////////////////////////////////////////////////////////////
// DayZ Config Generator: trerik4\city\modular\brick
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 10/31/2021, 12:13:05
// `py config_generator.py -o P:\ P:\trerik4\city\modular\brick`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_brick
    {
        units[] = { "Land_brick_beam_5m", "Land_brick_column_5m", "Land_brick_floor_10m", "Land_brick_floor_5m", "Land_brick_floor_multi_10m", "Land_brick_wall_10m", "Land_brick_wall_5m" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_brick_beam_5m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_brick_beam_5m";
        descriptionShort = "Autogenerated class Land_brick_beam_5m";
        model = "trerik4\city\modular\brick\brick_beam_5m.p3d";
    };
    class Land_brick_column_5m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_brick_column_5m";
        descriptionShort = "Autogenerated class Land_brick_column_5m";
        model = "trerik4\city\modular\brick\brick_column_5m.p3d";
    };
    class Land_brick_floor_10m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_brick_floor_10m";
        descriptionShort = "Autogenerated class Land_brick_floor_10m";
        model = "trerik4\city\modular\brick\brick_floor_10m.p3d";
    };
    class Land_brick_floor_5m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_brick_floor_5m";
        descriptionShort = "Autogenerated class Land_brick_floor_5m";
        model = "trerik4\city\modular\brick\brick_floor_5m.p3d";
    };
    class Land_brick_floor_multi_10m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_brick_floor_multi_10m";
        descriptionShort = "Autogenerated class Land_brick_floor_multi_10m";
        model = "trerik4\city\modular\brick\brick_floor_multi_10m.p3d";
    };
    class Land_brick_wall_10m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_brick_wall_10m";
        descriptionShort = "Autogenerated class Land_brick_wall_10m";
        model = "trerik4\city\modular\brick\brick_wall_10m.p3d";
    };
    class Land_brick_wall_5m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_brick_wall_5m";
        descriptionShort = "Autogenerated class Land_brick_wall_5m";
        model = "trerik4\city\modular\brick\brick_wall_5m.p3d";
    };
};