//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\city\decals
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 05/08/2022, 11:43:04
// `py config_generator.py -d -o F:\DayZ F:\DayZ\trerik4\city\decals`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_decals
    {
        units[] = { "Land_concrete1_decal_messy_5", "Land_concrete1_decal_messy_5_nolc" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_concrete1_decal_messy_5: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_concrete1_decal_messy_5";
        descriptionShort = "Autogenerated class Land_concrete1_decal_messy_5";
        model = "trerik4\city\decals\concrete1_decal_messy_5.p3d";
    };
    class Land_concrete1_decal_messy_5_nolc: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_concrete1_decal_messy_5_nolc";
        descriptionShort = "Autogenerated class Land_concrete1_decal_messy_5_nolc";
        model = "trerik4\city\decals\concrete1_decal_messy_5_nolc.p3d";
    };
};