//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\city\tunnel
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 01/20/2022, 21:30:21
// `py config_generator.py -s -r -d -o F:\DayZ P:\trerik4\city\tunnel`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_tunnel
    {
        units[] = { "Land_stone_moss_wall", "Land_tunnel" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_stone_moss_wall: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_stone_moss_wall";
        descriptionShort = "Autogenerated class Land_stone_moss_wall";
        model = "trerik4\city\tunnel\stone_moss_wall.p3d";
    };
    class Land_tunnel: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_tunnel";
        descriptionShort = "Autogenerated class Land_tunnel";
        model = "trerik4\city\tunnel\tunnel.p3d";
    };
};