//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\military\trucks
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 09/11/2021, 20:02:17
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class generated_trucks
    {
        units[] = { "Land_truck_grey_tarp1" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_truck_grey_tarp1: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_truck_grey_tarp1";
        descriptionShort = "Autogenerated class Land_truck_grey_tarp1";
        model = "trerik4\military\trucks\truck_grey_tarp1.p3d";
    };
};