//////////////////////////////////////////////////////////////
// DayZ Config Generator: \trerik4\city
// Produced from Kerkkoh's DayZ Config Generator version 1.0.0
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 02/08/2021, 21:44:10
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_artifacts
    {
        units[] = { "Land_cross", "Land_pilar", "Land_artifact_statue" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_cross: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_cross";
        descriptionShort = "Autogenerated class Land_cross";
        model = "trerik4\city\artifacts\cross\cross.p3d";
    };
    class Land_pilar: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_pilar";
        descriptionShort = "Autogenerated class Land_pilar";
        model = "trerik4\city\artifacts\pilar\pilar.p3d";
    };
    class Land_artifact_statue: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_artifact_statue";
        descriptionShort = "Autogenerated class Land_artifact_statue";
        model = "trerik4\city\artifacts\statue\artifact_statue.p3d";
    };
};