//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\city\underground\secondary
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 01/20/2022, 21:37:01
// `py config_generator.py -d -o F:\DayZ P:\trerik4\city\underground\secondary`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_secondary
    {
        units[] = { "Land_sewer_10", "Land_sewer_10_45", "Land_sewer_10_tcross", "Land_sewer_entrance", "Land_sewer_entrance_no_rooad", "Land_sewer_withdoor" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_sewer_10: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sewer_10";
        descriptionShort = "Autogenerated class Land_sewer_10";
        model = "trerik4\city\underground\secondary\sewer_10.p3d";
    };
    class Land_sewer_10_45: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sewer_10_45";
        descriptionShort = "Autogenerated class Land_sewer_10_45";
        model = "trerik4\city\underground\secondary\sewer_10_45.p3d";
    };
    class Land_sewer_10_tcross: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sewer_10_tcross";
        descriptionShort = "Autogenerated class Land_sewer_10_tcross";
        model = "trerik4\city\underground\secondary\sewer_10_tcross.p3d";
    };
    class Land_sewer_entrance: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sewer_entrance";
        descriptionShort = "Autogenerated class Land_sewer_entrance";
		model = "trerik4\city\underground\secondary\sewer_entrance.p3d";
	};
    class Land_sewer_entrance_no_rooad: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sewer_entrance_no_rooad";
        descriptionShort = "Autogenerated class Land_sewer_entrance_no_rooad";
		model = "trerik4\city\underground\secondary\sewer_entrance_no_rooad.p3d";
	};
    class Land_sewer_withdoor: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sewer_withdoor";
        descriptionShort = "Autogenerated class Land_sewer_withdoor";
		model = "trerik4\city\underground\secondary\sewer_withdoor.p3d";
		class Doors
		{
			class Door1
			{
				displayName = "Door 1";
				component = "door1";
				soundPos = "door1_action";
				animPeriod = 1.0;
				initPhase = 0.0;
				initOpened = 0.0;
				soundOpen = "doorMetalSmallOpen";
				soundClose = "doorMetalSmallClose";
				soundLocked = "doorMetalSmallRattle";
				soundOpenABit = "doorMetalSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 1000;
				};
			};
			class GlobalArmor
			{
				class Projectile
				{
					class Health { damage = 0; };
					class Blood { damage = 0; };
					class Shock { damage = 0; };
				};
				class Melee
				{
					class Health { damage = 0; };
					class Blood { damage = 0; };
					class Shock { damage = 0; };
				};
			};
			class DamageZones
			{
				class Door1
				{
					class Health
					{
						hitpoints = 1000;
						transferToGlobalCoef = 0;
					};
					componentNames[] = {"door1"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile
						{
							class Health { damage = 2; };
							class Blood { damage = 0; };
							class Shock { damage = 0; };
						};
						class Melee
						{
							class Health { damage = 2.5; };
							class Blood { damage = 0; };
							class Shock { damage = 0; };
						};
					};
				};
			};
		};
	};
};