//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\city\signs
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 03/11/2022, 21:57:23
// `py config_generator.py -s -r -d -o F:\DayZ P:\trerik4\city\signs`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_signs
    {
        units[] = { "Land_sign_kebabnino", "Land_sign_nyheim", "Land_sign_nyvoll", "Land_sign_oya", "Land_sign_rodal", "Land_sign_sorbu", "Land_sign_utkjaer", "Land_sign_vestby", "Land_sign_vika", "Land_sign_beer", "Land_sign_blow", "Land_sign_deadcity", "Land_sign_drmax", "Land_sign_hospital", "Land_sign_notacola", "Land_sign_notacola2", "Land_sign_starducks", "Land_sign_vertical_lightsoff", "Land_sign_vertical_starducks", "Land_sign_vodka" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
	// Town stuff
    class Land_sign_kebabnino: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_kebabnino";
        descriptionShort = "Autogenerated class Land_sign_kebabnino";
        model = "trerik4\city\signs\towns\sign_kebabnino.p3d";
    };
    class Land_sign_nyheim: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_nyheim";
        descriptionShort = "Autogenerated class Land_sign_nyheim";
        model = "trerik4\city\signs\towns\sign_nyheim.p3d";
    };
    class Land_sign_nyvoll: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_nyvoll";
        descriptionShort = "Autogenerated class Land_sign_nyvoll";
        model = "trerik4\city\signs\towns\sign_nyvoll.p3d";
    };
    class Land_sign_oya: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_oya";
        descriptionShort = "Autogenerated class Land_sign_oya";
        model = "trerik4\city\signs\towns\sign_oya.p3d";
    };
    class Land_sign_rodal: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_rodal";
        descriptionShort = "Autogenerated class Land_sign_rodal";
        model = "trerik4\city\signs\towns\sign_rodal.p3d";
    };
    class Land_sign_sorbu: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_sorbu";
        descriptionShort = "Autogenerated class Land_sign_sorbu";
        model = "trerik4\city\signs\towns\sign_sorbu.p3d";
    };
    class Land_sign_utkjaer: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_utkjaer";
        descriptionShort = "Autogenerated class Land_sign_utkjaer";
        model = "trerik4\city\signs\towns\sign_utkjaer.p3d";
    };
    class Land_sign_vestby: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_vestby";
        descriptionShort = "Autogenerated class Land_sign_vestby";
        model = "trerik4\city\signs\towns\sign_vestby.p3d";
    };
    class Land_sign_vika: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_vika";
        descriptionShort = "Autogenerated class Land_sign_vika";
        model = "trerik4\city\signs\towns\sign_vika.p3d";
    };
	// My stuff
    class Land_sign_beer: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_beer";
        descriptionShort = "Autogenerated class Land_sign_beer";
        model = "trerik4\city\signs\sign_beer.p3d";
    };
    class Land_sign_blow: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_blow";
        descriptionShort = "Autogenerated class Land_sign_blow";
        model = "trerik4\city\signs\sign_blow.p3d";
    };
    class Land_sign_deadcity: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_deadcity";
        descriptionShort = "Autogenerated class Land_sign_deadcity";
        model = "trerik4\city\signs\sign_deadcity.p3d";
    };
    class Land_sign_drmax: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_drmax";
        descriptionShort = "Autogenerated class Land_sign_drmax";
        model = "trerik4\city\signs\sign_drmax.p3d";
    };
    class Land_sign_hospital: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_hospital";
        descriptionShort = "Autogenerated class Land_sign_hospital";
        model = "trerik4\city\signs\sign_hospital.p3d";
    };
    class Land_sign_notacola: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_notacola";
        descriptionShort = "Autogenerated class Land_sign_notacola";
        model = "trerik4\city\signs\sign_notacola.p3d";
    };
    class Land_sign_notacola2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_notacola2";
        descriptionShort = "Autogenerated class Land_sign_notacola2";
        model = "trerik4\city\signs\sign_notacola2.p3d";
    };
    class Land_sign_starducks: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_starducks";
        descriptionShort = "Autogenerated class Land_sign_starducks";
        model = "trerik4\city\signs\sign_starducks.p3d";
    };
    class Land_sign_vertical_lightsoff: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_vertical_lightsoff";
        descriptionShort = "Autogenerated class Land_sign_vertical_lightsoff";
        model = "trerik4\city\signs\sign_vertical_lightsoff.p3d";
		hiddenSelections[] = {"screen"};
		hiddenSelectionsTextures[] = {"trerik4\city\signs\data\sign_starducks_vertical.paa"};
		hiddenSelectionsMaterials[] = {"trerik4\city\signs\data\electric_sign.rvmat"};
    };
    class Land_sign_vertical_starducks: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_vertical_starducks";
        descriptionShort = "Autogenerated class Land_sign_vertical_starducks";
        model = "trerik4\city\signs\sign_vertical_starducks.p3d";
		hiddenSelections[] = {"screen"};
		hiddenSelectionsTextures[] = {"trerik4\city\signs\data\sign_starducks_vertical.paa"};
		hiddenSelectionsMaterials[] = {"trerik4\city\signs\data\electric_sign.rvmat"};

		class AnimatedTexture {
			enabled = 1;
			loop = 1;
			increment = 1;
			interval = 4000;
			intervalRandomness = 1000;
			renderDistance = 40.0;
			distanceResetsToDefault = 1;
			selectionToAnimate = "screen";
			hiddenSelectionsTexturePhases[] = {"trerik4\city\signs\data\sign_starducks_vertical.paa", "trerik4\city\signs\data\sign_plikt_vertical.paa", "trerik4\city\signs\data\sign_starducks_vertical1.paa", "trerik4\city\signs\data\sign_starducks_vertical2.paa"};
			hiddenSelectionsMaterialPhases[] = {"", "", "", ""};
		};
    };
    class Land_sign_vodka: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_vodka";
        descriptionShort = "Autogenerated class Land_sign_vodka";
        model = "trerik4\city\signs\sign_vodka.p3d";
    };
};