//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\city\graffiti
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 04/05/2022, 13:08:13
// `py config_generator.py -d -o F:\DayZ P:\trerik4\city\graffiti`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_graffiti
    {
        units[] = { "Land_graffiti1", "Land_graffiti10", "Land_graffiti11", "Land_graffiti12", "Land_graffiti13", "Land_graffiti2", "Land_graffiti3", "Land_graffiti4", "Land_graffiti5", "Land_graffiti6", "Land_graffiti7", "Land_graffiti8", "Land_graffiti9", "Land_graffitiamazon", "Land_graffitiblowforcar", "Land_graffitiblub", "Land_graffitibrandon", "Land_graffiticabron2", "Land_graffiticitizenswearyourmasks", "Land_graffitidead", "Land_graffitidonttrust", "Land_graffitidonttrustthem", "Land_graffitifamilia", "Land_graffitifiteback", "Land_graffitigvt", "Land_graffitiholy", "Land_graffitiinfection", "Land_graffitikill", "Land_graffitinathan", "Land_graffitineom1", "Land_graffitinolooting", "Land_graffitinosmoking", "Land_graffitinotabunker", "Land_graffitipipsi", "Land_graffitiremember", "Land_graffitiresistance", "Land_graffitisilenced", "Land_graffitislavarossii", "Land_graffitisovietengineeringpristine", "Land_graffitisovietengineeringruined", "Land_graffitispraying", "Land_graffitisyndicate", "Land_graffitisyndicate2", "Land_graffitisyndicatestar", "Land_graffititend", "Land_graffititrustearned", "Land_graffitiwar", "Land_graffitiwhyshouldi", "Land_graffitixiv", "Land_graffitiyoumatter" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_graffiti1: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti1";
        descriptionShort = "Autogenerated class Land_graffiti1";
        model = "trerik4\city\graffiti\graffiti1.p3d";
    };
    class Land_graffiti10: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti10";
        descriptionShort = "Autogenerated class Land_graffiti10";
        model = "trerik4\city\graffiti\graffiti10.p3d";
    };
    class Land_graffiti11: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti11";
        descriptionShort = "Autogenerated class Land_graffiti11";
        model = "trerik4\city\graffiti\graffiti11.p3d";
    };
    class Land_graffiti12: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti12";
        descriptionShort = "Autogenerated class Land_graffiti12";
        model = "trerik4\city\graffiti\graffiti12.p3d";
    };
    class Land_graffiti13: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti13";
        descriptionShort = "Autogenerated class Land_graffiti13";
        model = "trerik4\city\graffiti\graffiti13.p3d";
    };
    class Land_graffiti2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti2";
        descriptionShort = "Autogenerated class Land_graffiti2";
        model = "trerik4\city\graffiti\graffiti2.p3d";
    };
    class Land_graffiti3: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti3";
        descriptionShort = "Autogenerated class Land_graffiti3";
        model = "trerik4\city\graffiti\graffiti3.p3d";
    };
    class Land_graffiti4: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti4";
        descriptionShort = "Autogenerated class Land_graffiti4";
        model = "trerik4\city\graffiti\graffiti4.p3d";
    };
    class Land_graffiti5: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti5";
        descriptionShort = "Autogenerated class Land_graffiti5";
        model = "trerik4\city\graffiti\graffiti5.p3d";
    };
    class Land_graffiti6: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti6";
        descriptionShort = "Autogenerated class Land_graffiti6";
        model = "trerik4\city\graffiti\graffiti6.p3d";
    };
    class Land_graffiti7: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti7";
        descriptionShort = "Autogenerated class Land_graffiti7";
        model = "trerik4\city\graffiti\graffiti7.p3d";
    };
    class Land_graffiti8: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti8";
        descriptionShort = "Autogenerated class Land_graffiti8";
        model = "trerik4\city\graffiti\graffiti8.p3d";
    };
    class Land_graffiti9: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiti9";
        descriptionShort = "Autogenerated class Land_graffiti9";
        model = "trerik4\city\graffiti\graffiti9.p3d";
    };
    class Land_graffitiamazon: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiamazon";
        descriptionShort = "Autogenerated class Land_graffitiamazon";
        model = "trerik4\city\graffiti\graffitiamazon.p3d";
    };
    class Land_graffitiblowforcar: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiblowforcar";
        descriptionShort = "Autogenerated class Land_graffitiblowforcar";
        model = "trerik4\city\graffiti\graffitiblowforcar.p3d";
    };
    class Land_graffitiblub: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiblub";
        descriptionShort = "Autogenerated class Land_graffitiblub";
        model = "trerik4\city\graffiti\graffitiblub.p3d";
    };
    class Land_graffitibrandon: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitibrandon";
        descriptionShort = "Autogenerated class Land_graffitibrandon";
        model = "trerik4\city\graffiti\graffitibrandon.p3d";
    };
    class Land_graffiticabron2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiticabron2";
        descriptionShort = "Autogenerated class Land_graffiticabron2";
        model = "trerik4\city\graffiti\graffiticabron2.p3d";
    };
    class Land_graffiticitizenswearyourmasks: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffiticitizenswearyourmasks";
        descriptionShort = "Autogenerated class Land_graffiticitizenswearyourmasks";
        model = "trerik4\city\graffiti\graffiticitizenswearyourmasks.p3d";
    };
    class Land_graffitidead: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitidead";
        descriptionShort = "Autogenerated class Land_graffitidead";
        model = "trerik4\city\graffiti\graffitidead.p3d";
    };
    class Land_graffitidonttrust: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitidonttrust";
        descriptionShort = "Autogenerated class Land_graffitidonttrust";
        model = "trerik4\city\graffiti\graffitidonttrust.p3d";
    };
    class Land_graffitidonttrustthem: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitidonttrustthem";
        descriptionShort = "Autogenerated class Land_graffitidonttrustthem";
        model = "trerik4\city\graffiti\graffitidonttrustthem.p3d";
    };
    class Land_graffitifamilia: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitifamilia";
        descriptionShort = "Autogenerated class Land_graffitifamilia";
        model = "trerik4\city\graffiti\graffitifamilia.p3d";
    };
    class Land_graffitifiteback: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitifiteback";
        descriptionShort = "Autogenerated class Land_graffitifiteback";
        model = "trerik4\city\graffiti\graffitifiteback.p3d";
    };
    class Land_graffitigaeonce: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitigaeonce";
        descriptionShort = "Autogenerated class Land_graffitigaeonce";
        model = "trerik4\city\graffiti\graffitigaeonce.p3d";
    };
    class Land_graffitigvt: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitigvt";
        descriptionShort = "Autogenerated class Land_graffitigvt";
        model = "trerik4\city\graffiti\graffitigvt.p3d";
    };
    class Land_graffitiholy: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiholy";
        descriptionShort = "Autogenerated class Land_graffitiholy";
        model = "trerik4\city\graffiti\graffitiholy.p3d";
    };
    class Land_graffitiinfection: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiinfection";
        descriptionShort = "Autogenerated class Land_graffitiinfection";
        model = "trerik4\city\graffiti\graffitiinfection.p3d";
    };
    class Land_graffitikill: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitikill";
        descriptionShort = "Autogenerated class Land_graffitikill";
        model = "trerik4\city\graffiti\graffitikill.p3d";
    };
    class Land_graffitinathan: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitinathan";
        descriptionShort = "Autogenerated class Land_graffitinathan";
        model = "trerik4\city\graffiti\graffitinathan.p3d";
    };
    class Land_graffitineom1: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitineom1";
        descriptionShort = "Autogenerated class Land_graffitineom1";
        model = "trerik4\city\graffiti\graffitineom1.p3d";
    };
    class Land_graffitinolooting: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitinolooting";
        descriptionShort = "Autogenerated class Land_graffitinolooting";
        model = "trerik4\city\graffiti\graffitinolooting.p3d";
    };
    class Land_graffitinosmoking: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitinosmoking";
        descriptionShort = "Autogenerated class Land_graffitinosmoking";
        model = "trerik4\city\graffiti\graffitinosmoking.p3d";
    };
    class Land_graffitinotabunker: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitinotabunker";
        descriptionShort = "Autogenerated class Land_graffitinotabunker";
        model = "trerik4\city\graffiti\graffitinotabunker.p3d";
    };
    class Land_graffitipipsi: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitipipsi";
        descriptionShort = "Autogenerated class Land_graffitipipsi";
        model = "trerik4\city\graffiti\graffitipipsi.p3d";
    };
    class Land_graffitiremember: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiremember";
        descriptionShort = "Autogenerated class Land_graffitiremember";
        model = "trerik4\city\graffiti\graffitiremember.p3d";
    };
    class Land_graffitiresistance: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiresistance";
        descriptionShort = "Autogenerated class Land_graffitiresistance";
        model = "trerik4\city\graffiti\graffitiresistance.p3d";
    };
    class Land_graffitisilenced: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitisilenced";
        descriptionShort = "Autogenerated class Land_graffitisilenced";
        model = "trerik4\city\graffiti\graffitisilenced.p3d";
    };
    class Land_graffitislavarossii: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitislavarossii";
        descriptionShort = "Autogenerated class Land_graffitislavarossii";
        model = "trerik4\city\graffiti\graffitislavarossii.p3d";
    };
    class Land_graffitisovietengineeringpristine: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitisovietengineeringpristine";
        descriptionShort = "Autogenerated class Land_graffitisovietengineeringpristine";
        model = "trerik4\city\graffiti\graffitisovietengineeringpristine.p3d";
    };
    class Land_graffitisovietengineeringruined: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitisovietengineeringruined";
        descriptionShort = "Autogenerated class Land_graffitisovietengineeringruined";
        model = "trerik4\city\graffiti\graffitisovietengineeringruined.p3d";
    };
    class Land_graffitispraying: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitispraying";
        descriptionShort = "Autogenerated class Land_graffitispraying";
        model = "trerik4\city\graffiti\graffitispraying.p3d";
    };
    class Land_graffitisyndicate: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitisyndicate";
        descriptionShort = "Autogenerated class Land_graffitisyndicate";
        model = "trerik4\city\graffiti\graffitisyndicate.p3d";
    };
    class Land_graffitisyndicate2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitisyndicate2";
        descriptionShort = "Autogenerated class Land_graffitisyndicate2";
        model = "trerik4\city\graffiti\graffitisyndicate2.p3d";
    };
    class Land_graffitisyndicatestar: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitisyndicatestar";
        descriptionShort = "Autogenerated class Land_graffitisyndicatestar";
        model = "trerik4\city\graffiti\graffitisyndicatestar.p3d";
    };
    class Land_graffititend: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffititend";
        descriptionShort = "Autogenerated class Land_graffititend";
        model = "trerik4\city\graffiti\graffititend.p3d";
    };
    class Land_graffititrustearned: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffititrustearned";
        descriptionShort = "Autogenerated class Land_graffititrustearned";
        model = "trerik4\city\graffiti\graffititrustearned.p3d";
    };
    class Land_graffitiwar: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiwar";
        descriptionShort = "Autogenerated class Land_graffitiwar";
        model = "trerik4\city\graffiti\graffitiwar.p3d";
    };
    class Land_graffitiwhyshouldi: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiwhyshouldi";
        descriptionShort = "Autogenerated class Land_graffitiwhyshouldi";
        model = "trerik4\city\graffiti\graffitiwhyshouldi.p3d";
    };
    class Land_graffitixiv: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitixiv";
        descriptionShort = "Autogenerated class Land_graffitixiv";
        model = "trerik4\city\graffiti\graffitixiv.p3d";
    };
    class Land_graffitiyoumatter: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_graffitiyoumatter";
        descriptionShort = "Autogenerated class Land_graffitiyoumatter";
        model = "trerik4\city\graffiti\graffitiyoumatter.p3d";
    };
};