class CfgPatches
{
	class trerik4_bunker
	{
		units[] = {"Land_bunker_int_beam","Land_bunker_int_column","Land_bunker_int_widecolumn","Land_bunkerfloor","Land_bunkerfloor_ext","Land_bunkerfloor_ext_20","Land_bunkerfloor_half","Land_bunkerfloor_vertical","Land_bunkerhole","Land_bunkerwall_half","Land_bunkerwall_int_half","Land_bunkerwall_int_half_snap","Land_bunkerwall_int_tall","Land_bunkerwall_tall","Land_tarmacfloor","Land_tarmacfloor_20"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data"};
	};
};
class CfgVehicles
{
	class HouseNoDestruct;
	class Land_bunker_int_beam: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunker_int_beam";
		descriptionShort = "Autogenerated class Land_bunker_int_beam";
		model = "trerik4\city\modular\bunker\bunker_int_beam.p3d";
	};
	class Land_bunker_int_column: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunker_int_column";
		descriptionShort = "Autogenerated class Land_bunker_int_column";
		model = "trerik4\city\modular\bunker\bunker_int_column.p3d";
	};
	class Land_bunker_int_widecolumn: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunker_int_widecolumn";
		descriptionShort = "Autogenerated class Land_bunker_int_widecolumn";
		model = "trerik4\city\modular\bunker\bunker_int_widecolumn.p3d";
	};
	class Land_bunkerfloor: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerfloor";
		descriptionShort = "Autogenerated class Land_bunkerfloor";
		model = "trerik4\city\modular\bunker\bunkerfloor.p3d";
	};
	class Land_bunkerfloor_ext: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerfloor_ext";
		descriptionShort = "Autogenerated class Land_bunkerfloor_ext";
		model = "trerik4\city\modular\bunker\bunkerfloor_ext.p3d";
	};
	class Land_bunkerfloor_ext_20: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerfloor_ext_20";
		descriptionShort = "Autogenerated class Land_bunkerfloor_ext_20";
		model = "trerik4\city\modular\bunker\bunkerfloor_ext_20.p3d";
	};
	class Land_bunkerfloor_half: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerfloor_half";
		descriptionShort = "Autogenerated class Land_bunkerfloor_half";
		model = "trerik4\city\modular\bunker\bunkerfloor_half.p3d";
	};
	class Land_bunkerfloor_vertical: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerfloor_vertical";
		descriptionShort = "Autogenerated class Land_bunkerfloor_vertical";
		model = "trerik4\city\modular\bunker\bunkerfloor_vertical.p3d";
	};
	class Land_bunkerhole: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerhole";
		descriptionShort = "Autogenerated class Land_bunkerhole";
		model = "trerik4\city\modular\bunker\bunkerhole.p3d";
	};
	class Land_bunkerwall_half: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerwall_half";
		descriptionShort = "Autogenerated class Land_bunkerwall_half";
		model = "trerik4\city\modular\bunker\bunkerwall_half.p3d";
	};
	class Land_bunkerwall_int_half: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerwall_int_half";
		descriptionShort = "Autogenerated class Land_bunkerwall_int_half";
		model = "trerik4\city\modular\bunker\bunkerwall_int_half.p3d";
	};
	class Land_bunkerwall_int_half_snap: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerwall_int_half_snap";
		descriptionShort = "Autogenerated class Land_bunkerwall_int_half_snap";
		model = "trerik4\city\modular\bunker\bunkerwall_int_half_snap.p3d";
	};
	class Land_bunkerwall_int_tall: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerwall_int_tall";
		descriptionShort = "Autogenerated class Land_bunkerwall_int_tall";
		model = "trerik4\city\modular\bunker\bunkerwall_int_tall.p3d";
	};
	class Land_bunkerwall_tall: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_bunkerwall_tall";
		descriptionShort = "Autogenerated class Land_bunkerwall_tall";
		model = "trerik4\city\modular\bunker\bunkerwall_tall.p3d";
	};
	class Land_tarmacfloor: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_tarmacfloor";
		descriptionShort = "Autogenerated class Land_tarmacfloor";
		model = "trerik4\city\modular\bunker\tarmacfloor.p3d";
	};
	class Land_tarmacfloor_20: HouseNoDestruct
	{
		scope = 2;
		displayName = "Land_tarmacfloor_20";
		descriptionShort = "Autogenerated class Land_tarmacfloor_20";
		model = "trerik4\city\modular\bunker\tarmacfloor_20.p3d";
	};
};
