//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\city
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 01/20/2022, 21:49:08
// `py config_generator.py -d -o F:\DayZ P:\trerik4\city`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_city
    {
        units[] = { "Land_militarybox", "Land_militarybox_wooden" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_militarybox: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_militarybox";
        descriptionShort = "Autogenerated class Land_militarybox";
        model = "trerik4\city\props\militarybox.p3d";
    };
    class Land_militarybox_wooden: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_militarybox_wooden";
        descriptionShort = "Autogenerated class Land_militarybox_wooden";
        model = "trerik4\city\props\militarybox_wooden.p3d";
		class Doors
		{
			class Door1
			{
				displayName = "Door 1";
				component = "door1";
				soundPos = "door1_action";
				animPeriod = 1.0;
				initPhase = 0.0;
				initOpened = 0.5;
				soundOpen = "doorWoodSmallOpen";
				soundClose = "doorWoodSmallClose";
				soundLocked = "doorWoodSmallRattle";
				soundOpenABit = "doorWoodSmallOpenABit";
			};
		};
		class DamageSystem
		{
			class GlobalHealth
			{
				class Health
				{
					hitpoints = 1000;
				};
			};
			class GlobalArmor
			{
				class Projectile
				{
					class Health { damage = 0; };
					class Blood { damage = 0; };
					class Shock { damage = 0; };
				};
				class Melee
				{
					class Health { damage = 0; };
					class Blood { damage = 0; };
					class Shock { damage = 0; };
				};
			};
			class DamageZones
			{
				class Door1
				{
					class Health
					{
						hitpoints = 1000;
						transferToGlobalCoef = 0;
					};
					componentNames[] = {"door1"};
					fatalInjuryCoef = -1;
					class ArmorType
					{
						class Projectile
						{
							class Health { damage = 2; };
							class Blood { damage = 0; };
							class Shock { damage = 0; };
						};
						class Melee
						{
							class Health { damage = 2.5; };
							class Blood { damage = 0; };
							class Shock { damage = 0; };
						};
					};
				};
			};
		};
    };
    class Land_lootbox_wooden_residential: Land_militarybox_wooden
    {
        scope = 2;
        displayName = "Land_lootbox_wooden_residential";
        descriptionShort = "Autogenerated class Land_lootbox_wooden_residential";
        model = "trerik4\city\props\lootbox_wooden_residential.p3d";
    };
    class Land_lootbox_wooden_industrial: Land_militarybox_wooden
    {
        scope = 2;
        displayName = "Land_lootbox_wooden_industrial";
        descriptionShort = "Autogenerated class Land_lootbox_wooden_industrial";
        model = "trerik4\city\props\lootbox_wooden_industrial.p3d";
    };
};