//////////////////////////////////////////////////////////////
// DayZ Config Generator: trerik4\city\modular\wood
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 10/31/2021, 12:13:16
// `py config_generator.py -o P:\ P:\trerik4\city\modular\wood`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_wood
    {
        units[] = { "Land_wood_floor_10m", "Land_wood_floor_5m", "Land_wood_thinwall_5m" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_wood_floor_10m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_wood_floor_10m";
        descriptionShort = "Autogenerated class Land_wood_floor_10m";
        model = "trerik4\city\modular\wood\wood_floor_10m.p3d";
    };
    class Land_wood_floor_5m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_wood_floor_5m";
        descriptionShort = "Autogenerated class Land_wood_floor_5m";
        model = "trerik4\city\modular\wood\wood_floor_5m.p3d";
    };
    class Land_wood_thinwall_5m: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_wood_thinwall_5m";
        descriptionShort = "Autogenerated class Land_wood_thinwall_5m";
        model = "trerik4\city\modular\wood\wood_thinwall_5m.p3d";
    };
};