//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\military\missile_launcher
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 01/21/2022, 01:56:21
// `py config_generator.py -d -o F:\DayZ P:\trerik4\military\missile_launcher`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_missile_launcher
    {
        units[] = { "Land_engine_raptor", "Land_military_truck_camonet", "Land_military_truck_covered", "Land_military_truck_grey", "Land_military_truck_grey_covered", "Land_military_truck_red", "Land_missile", "Land_missile2", "Land_missile3", "Land_missile_launcher", "Land_missile_launcher_only_down", "Land_missile_launcher_only_up", "Land_nuclear_missile" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_engine_raptor: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_engine_raptor";
        descriptionShort = "Autogenerated class Land_engine_raptor";
        model = "trerik4\military\missile_launcher\engine_raptor.p3d";
    };
    class Land_military_truck_camonet: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_military_truck_camonet";
        descriptionShort = "Autogenerated class Land_military_truck_camonet";
        model = "trerik4\military\missile_launcher\military_truck_camonet.p3d";
    };
    class Land_military_truck_covered: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_military_truck_covered";
        descriptionShort = "Autogenerated class Land_military_truck_covered";
        model = "trerik4\military\missile_launcher\military_truck_covered.p3d";
    };
    class Land_military_truck_grey: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_military_truck_grey";
        descriptionShort = "Autogenerated class Land_military_truck_grey";
        model = "trerik4\military\missile_launcher\military_truck_grey.p3d";
    };
    class Land_military_truck_grey_covered: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_military_truck_grey_covered";
        descriptionShort = "Autogenerated class Land_military_truck_grey_covered";
        model = "trerik4\military\missile_launcher\military_truck_grey_covered.p3d";
    };
    class Land_military_truck_red: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_military_truck_red";
        descriptionShort = "Autogenerated class Land_military_truck_red";
        model = "trerik4\military\missile_launcher\military_truck_red.p3d";
    };
    class Land_missile: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_missile";
        descriptionShort = "Autogenerated class Land_missile";
        model = "trerik4\military\missile_launcher\missile.p3d";
    };
    class Land_missile2: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_missile2";
        descriptionShort = "Autogenerated class Land_missile2";
        model = "trerik4\military\missile_launcher\missile2.p3d";
    };
    class Land_missile3: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_missile3";
        descriptionShort = "Autogenerated class Land_missile3";
        model = "trerik4\military\missile_launcher\missile3.p3d";
    };
    class Land_missile_launcher: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_missile_launcher";
        descriptionShort = "Autogenerated class Land_missile_launcher";
        model = "trerik4\military\missile_launcher\missile_launcher.p3d";
    };
    class Land_missile_launcher_only_down: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_missile_launcher_only_down";
        descriptionShort = "Autogenerated class Land_missile_launcher_only_down";
        model = "trerik4\military\missile_launcher\missile_launcher_only_down.p3d";
    };
    class Land_missile_launcher_only_up: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_missile_launcher_only_up";
        descriptionShort = "Autogenerated class Land_missile_launcher_only_up";
        model = "trerik4\military\missile_launcher\missile_launcher_only_up.p3d";
    };
    class Land_nuclear_missile: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_nuclear_missile";
        descriptionShort = "Autogenerated class Land_nuclear_missile";
        model = "trerik4\military\missile_launcher\nuclear_missile.p3d";
    };
};