//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\dpl\plants
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 03/23/2022, 01:01:59
// `py config_generator.py -d -o F:\DayZ P:\trerik4\dpl\plants`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_plants
    {
        units[] = { "Land_p_fiberPlant_EP1" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_p_fiberPlant_EP1: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_p_fiberPlant_EP1";
        descriptionShort = "Autogenerated class Land_p_fiberPlant_EP1";
        model = "trerik4\dpl\plants\p_fiberPlant_EP1.p3d";
    };
};