//////////////////////////////////////////////////////////////
// DayZ Config Generator: P:\trerik4\military\signs
// Produced from Kerkkoh's DayZ Config Generator version 1.0.1
// https://github.com/kerkkoh/dayzconfiggen
// 'now' is 01/20/2022, 21:26:12
// `py config_generator.py -d -o F:\DayZ P:\trerik4\military\signs`
//////////////////////////////////////////////////////////////
class CfgPatches
{
    class trerik4_signs
    {
        units[] = { "Land_sign_military_area", "Land_sign_military_research_area", "Land_sign_military_training_area", "Land_sign_military_training_area_leaving" };
        weapons[] = {};
        requiredVersion = 0.1;
        requiredAddons[] = { "DZ_Data" };
    };
};
class CfgVehicles
{
	class HouseNoDestruct;
    class Land_sign_military_area: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_military_area";
        descriptionShort = "Autogenerated class Land_sign_military_area";
        model = "trerik4\military\signs\sign_military_area.p3d";
    };
    class Land_sign_military_research_area: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_military_research_area";
        descriptionShort = "Autogenerated class Land_sign_military_research_area";
        model = "trerik4\military\signs\sign_military_research_area.p3d";
    };
    class Land_sign_military_training_area: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_military_training_area";
        descriptionShort = "Autogenerated class Land_sign_military_training_area";
        model = "trerik4\military\signs\sign_military_training_area.p3d";
    };
    class Land_sign_military_training_area_leaving: HouseNoDestruct
    {
        scope = 2;
        displayName = "Land_sign_military_training_area_leaving";
        descriptionShort = "Autogenerated class Land_sign_military_training_area_leaving";
        model = "trerik4\military\signs\sign_military_training_area_leaving.p3d";
    };
};